### ISSUE TITLE
The file auth0-variables is not being used

### ISSUE THREAD

**Issue by adriatic** [auth0-community/auth0-aurelia-samples#11]
The code in the tutorial document creates the new instance of Auth0Lock as:

```
export class App {
  lock = new Auth0Lock('6f5Zun4YemkhNWS5hPiJjFyFlfu', 'aureliatools.auth0.com');
  isAuthenticated = false;
  
```
_Note that I mangled my ClientIS instance for my own security reasons_

The code in the repository suggests to use the file **[`auth0-variables.js`](https://github.com/auth0-community/auth0-aurelia-samples/blob/master/01-Login/auth0-variables.js.example)** instead.

I believe that keeping the credentials "outside" your javascript code is more in tune with Auth0 standard practice.

**Comment by adriatic** [comment]
Added later

Running the app with **[this line](https://github.com/auth0-community/auth0-aurelia-samples/blob/master/01-Login/src/app.js#L9)** unchanged (as different from this same instruction written in the form `lock = new Auth0Lock('6f5Zun4YemkhNWS5hPiJjFyFlfu', 'aureliatools.auth0.com');` as documented in the tutorial text. results with an error:

![image](https://cloud.githubusercontent.com/assets/2712405/24065648/27e327dc-0b43-11e7-878f-6c01c4a4a850.png)

where the error shown in the console as:

```
Uncaught Error: Error: An error occurred when fetching data.
    at index.js:470
(anonymous) @ index.js:470
```

is actually 

![image](https://cloud.githubusercontent.com/assets/2712405/24065666/4ca0a54a-0b43-11e7-9eb1-87530d4fdcd1.png)

this file **`index.js`** seems like a part of webpack - so something seems "cross linked"

**Comment by smoore4moma** [comment]
I agree with the basic issue here.  And it is one that is unfortunately too common with the Aurelia samples - you should always be able to do "Hello World!" examples without debugging for a day or two.  I see what is happening.  Basically the devs have bigger fish to fry, and that's true!  I like the idea of "au run --watch" but now I just use "npm install http-server".  The CLI time could have been better put to use with developer examples IMO.  More adopters, more code in prod, more acceptance of the framework.  I will use Auth0 with Aurelia but the Quick Start does need some work.  I will put a project on GitHub when I have time.

**Comment by beardaway** [comment]
Hey everyone!

Terribly sorry for such delay in response! At the time the tool hosted in the repo was developed we didn't have enough bandwidth to implement it further that's why we kinda decided to "outsource" it to our community developers.

For now we are gradually expanding the team and we're aiming that at some point in the future we'll be able to maintain and develop this repo more effectively. Sorry for any inconvenience!
