### ISSUE TITLE
Error: Route not found: /access_token=..

### ISSUE THREAD

**Issue by larserikfinholt** [auth0-community/auth0-aurelia-samples#15]
Hi!

Do I need to add some extra stuff into the router so that lock can get the accesstoken? After a lock-login the page is redirected to /access_token, but that route is not known by aurelia.

**Comment by smoore4moma** [comment]
Just put "/callback" in your list of allowed callback URLs (Auth0 setting), like this for example:

http://localhost:9000, http://localhost:9000/callback

**Comment by beardaway** [comment]
Hey @larserikfinholt ! Sorry for the delay in response but overall @smoore4moma was right, you can do it following the step he provided.

Some time ago we've started working on enhancing the OSS developer experience in our auth0-community repos by providing consistent communication and support for PRs and issues reviews but also redesigning the structure of our community repos so you can use and integrate those tools easier. 

Thanks a lot for help and one more time sorry for the delay in response!
