### ISSUE TITLE
How to edit auth0 docs?

### ISSUE THREAD

**Issue by adriatic** [auth0-community/auth0-aurelia-samples#29]
I am using the **[angularjs](https://github.com/auth0/docs/tree/master/articles/quickstart/spa/angularjs)** as the model for my questions, since the **[aurelia](https://github.com/auth0/docs/tree/master/articles/quickstart/spa/aurelia)** section is incomplete and as such insufficiently "general"

1. The new aurelia folder should contain all of the files/ folders shown below:
    
    ![image](https://user-images.githubusercontent.com/2712405/41293910-9f816e94-6e24-11e8-87d0-08851eb029e4.png)

2. The first "chapter" 01-Login should be placed in the **[_includes](https://github.com/auth0/docs/tree/master/articles/quickstart/spa/angularjs/_includes)** folder, named as _centralized_login.md. This folder should also contain the file **`_install_aurelia-auth0.md`**

3. The content of the actual **`[01-Login]()** chapter consists of Auth0 docs "macros" only:
    ````
     ---
    title: Login
    description: This tutorial demonstrates how to add user login to your application with Auth0
    budicon: 448
    ---

    <%= include('../../../_includes/_package', {
    org: 'auth0-samples',
    repo: 'auth0-angularjs-samples',
    path: '01-Login',
    requirements: [
        'AngularJS 1.6'
    ]
    }) %>

    <%= include('../_includes/_getting_started', { library: 'AngularJS', callback: 'http://localhost:3000/callback' }) %>

    <%= include('_includes/_install_angular_auth0') %>

    <%= include('_includes/_centralized_login') %>
    ````
    #### Why are not all chapters done this same way (separate macros from real text)?

4. Is there any document describing the creation of use of docker files in QS?

**Comment by aaguiarz** [comment]
You should include the ones that are not in the Aurelia directory (e.g. ../includes/_getting_started), but you don't need to add includes for the rest of the content (e.g. _includes/_install_angular_auth0). Some Quickstarts had to main .md files and we were able to reuse parts of the content that way, but it's not required.

About docker, we don't have any instructions, but if you take any existing file, like https://github.com/auth0-samples/auth0-angular-samples/blob/master/01-Login/Dockerfile, changes should be minimal.  In that one, you probably just need to change CMD ["npm", "start"] to CMD ["nps"] and it work.

**Comment by adriatic** [comment]
One more question, please: what is the recommended process for adding the QS docs? The obvious answer might be "fork the whole repo" and then create a PR for the small part I will change. Is there a shortcut, like starting to edit a specific folder directly on GitHub, which will trigger the fork, etc ...?

**Comment by aaguiarz** [comment]
No, you need to fork the repo. After forking it, you could create a branch in GitHub, and then clone just that branch in your local machine if you don't want to clone the whole repo, but I'm not sure if that will help much.
